### ISSUE TITLE
Trac dogu

### ISSUE THREAD

**Issue by tgrosser** [cloudogu/ecosystem#102]
[Trac](https://trac.edgewall.org) could be an alternative to Redmine. There seems to be an existing [plugin](https://trac-hacks.org/wiki/TracCasPlugin) for CAS auth. SCM-Manager has its own [plugin](https://www.scm-manager.org/plugins/scm-trac-plugin/) for Trac. Maybe this is a quick win for a dogu?

**Comment by ischindler** [comment]
I will go on and close this proposal or is this still a consideration?
