### ISSUE TITLE
update base system to ubuntu 16.04

### ISSUE THREAD

**Issue by sdorra** [cloudogu/ecosystem#128]
We should upgrade the base system to [ubuntu 16.04](https://wiki.ubuntu.com/XenialXerus/ReleaseNotes). Ubuntu 16.04 uses [systemd](https://freedesktop.org/wiki/Software/systemd/) as init system and this will hopefully fix some bugs we have with [upstart](http://upstart.ubuntu.com/index.html).

**Comment by robertauer** [comment]
Is this concerning the ecosystem-basebox, which is still on 14.04? Or is it concerning the ecosystem base container, which would mean it is not an issue anymore, because we are using alpine now?

**Comment by sdorra** [comment]
Yes, the issue targets the ecosystem-basebox.

**Comment by robertauer** [comment]
Note: The ecosystem-basebox in its own repository is deprecated. The current template for the basebox can be found in ecosystem/images/template.dev.json

**Comment by robertauer** [comment]
Note: Upstart-scripts for docker containers do not have to be refactored to work with systemd, because a new (re)start policy will be used as described in #236 .

**Comment by robertauer** [comment]
Problem: When the line `d-i time/zone string UTC` remains in the preseed file, the `timedatectl set-timezone` command used by the ces-setup fails, with log message:
> systemd-timedated[2606]: Failed to set time zone: Permission denied

(Or `Failed to set time zone: Access denied`, if you try to do it manually)
