### ISSUE TITLE
Find a better way to configure nexus and sonar

### ISSUE THREAD

**Issue by sdorra** [cloudogu/ecosystem#142]
We need a better way to configure nexus and sonarqube. At the moment the configuration is done with the rest api, that leads to polling (until the the service is up) and restarting of the service, which in turn leads to zombie processes and long, error prone service startups. 

We need a more elegant way like jenkins or scm-manager (e.g.: groovy init scripts).

**Comment by robertauer** [comment]
In Nexus, it may be possible to write template conf files, render them at startup and fill the conf/ directory with them.
https://books.sonatype.com/nexus-book/reference/install-sect-dirs.html

**Comment by sklein94** [comment]
SonarQube and Nexus have been updated many times and this seems not to be relevant anymore.
If still important, reopen the issue at:
* https://github.com/cloudogu/nexus
* https://github.com/cloudogu/sonar
