### ISSUE TITLE
Unauthorized access to rest api with username + password ("admin", "admin" working)

### ISSUE THREAD

**Issue by maltek709** [cloudogu/ecosystem#175]
If you try to access "${ECOSYSTEM_URL}/redmine/users.json" as an cesAdmin group user with username and password, it throws and 401 error. Trying to log in with user "admin" and password "admin" works.

**Comment by robertauer** [comment]
Redmine's default admin account is still created and active in our instances. This leads to problems like the one mentioned above, when you also try to login as a user called "admin". Redmine seems to verify the password against it's database before using cas, which leads to an denied access, if your cas admin password does not match the default admin's password. Therefore, the default admin account should be deleted.

**Comment by robertauer** [comment]
This also seems to lead to problems like https://github.com/cloudogu/ecosystem/issues/158
