### ISSUE TITLE
SSL issue git

### ISSUE THREAD

**Issue by schristann** [cloudogu/ecosystem#177]
At the moment there is no normal way to push code to ces, because of issues with ssl.

Example:
trio-pc-0082:~ TRIO$ git clone http://schristann@192.168.115.136/scm/git/blah
Cloning into 'blah'...
fatal: unable to access 'https://192.168.115.136/scm/git/blah/': SSL certificate problem: Invalid certificate chain

Setting "git config --global http.sslVerify false" is no solution, because the user will have serious security issues after setting this. We really have need of a "howto" containing advices installing certificates/trusts.

**Comment by ischindler** [comment]
@schristann Can you please check this issue and close it in case it's solved? Thank you!

**Comment by ischindler** [comment]
Seems to be the usual behavior with unsigned ssl certificates. Therefore the issue will be closed.
