### ISSUE TITLE
Redmine REST API access on first try

### ISSUE THREAD

**Issue by robertauer** [cloudogu/ecosystem#182]
The user should be enabled to access the Redmine REST API on first try. Until now, the REST API only works if the user has logged in at least once before.
Details:
At the first login (via browser or REST API) the user's database entry in the redmine_xyz/users table is created. Before this happens, the user is not granted any rights in Redmine, e.g. to read the /redmine/users.json.

**Comment by sklein94** [comment]
The Redmine-CAS-Plugin has been updated. This is now possible :)
