### ISSUE TITLE
Panic during installation

### ISSUE THREAD

**Issue by dhuchthausen** [cloudogu/ecosystem#184]
When I hit the "F5" button during the installation, the installation fails. I tested it with several different browsers (Chrome, Safari, Opera). I'm using Windows 7.

The ces-setup.log ends like this:
`panic: send on closed channel

goroutine 126 [running]:
panic(0xb1b6a0, 0xc82049e760)
        /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
github.com/cloudogu/ces-setup/setup.(*SetupContext).Start(0xc8201fd7c0)
        /home/ssdorra/Projects/go/src/github.com/cloudogu/ces-setup/setup/setupcontext.go:48 +0x3d2
created by github.com/cloudogu/ces-setup/rest.(*SetupController).StartSetup
        /home/ssdorra/Projects/go/src/github.com/cloudogu/ces-setup/rest/setup.go:92 +0x56`

**Comment by sdorra** [comment]
Should be fixed with version 0.3.0 of ces-setup.
