### ISSUE TITLE
Error message in UI during installation

### ISSUE THREAD

**Issue by dhuchthausen** [cloudogu/ecosystem#186]
During the installation of the dogus there permanently is an error message in the progress bar, nevertheless the installation continues.
![image](https://cloud.githubusercontent.com/assets/16819537/17203755/858262c6-54a1-11e6-97e9-11835f5ff3e6.png)

Im using Windows 7, and I've tried several different browsers (Chrome, Firefox, Safari), all show the error message.

**Comment by robertauer** [comment]
This issue occurred to me when I installed Cloudogu with all dogus but Jenkins. The installation with the exact same credentials including Jenkins was successful though.

**Comment by sdorra** [comment]
The problem is caused by an online virus scanner, which blocks the sse packets.
