### ISSUE TITLE
Error after starting redmine

### ISSUE THREAD

**Issue by mbehlendorf** [cloudogu/ecosystem#189]
I get:

> "admin" was authenticated but could not be created automatically in Redmine. It must be added manually.

**Comment by mbehlendorf** [comment]
Found the reason:
> Could not auto-create user: Email is invalid

I used `a@a` as email address.

**Comment by mbehlendorf** [comment]
Idea:
We could change the email validation in User Management & Setup.

**Comment by ischindler** [comment]
Closed because of a better described bug. #211
