### ISSUE TITLE
postfix should not use etcd for mynetworks

### ISSUE THREAD

**Issue by sdorra** [cloudogu/ecosystem#194]
At the moment the postfix container queries etcd for the mynetworks parameter [startup.sh](https://github.com/cloudogu/ecosystem/blob/develop/containers/postfix/startup.sh#L10). If we are switching to docker 1.12 and docker swarm, storing the overlay network information in etcd is not longer required. Instead we could use the network informations from the container itself (ifconfig).

**Comment by schristann** [comment]
Removed etcd usage and substituted it by using network config tools to determine config.
