### ISSUE TITLE
Update Sonatype Nexus to version 3

### ISSUE THREAD

**Issue by robertauer** [cloudogu/ecosystem#198]

**Comment by omilke** [comment]
I presume offering Nexus 3 OSS is a good thing to do.

However, last time I checked (and asked on Twitter),  there was no means of migrating Nexus OSS 2 to Nexus 3 OSS.

Back then, there has only been a way of migration for the commercial installations.

Might be different as of now.

**Comment by omilke** [comment]
Seems like in the meantime, there is way to update Nexus OSS 2 (starting with 2.14) to Nexus OSS 3.1

https://support.sonatype.com/hc/en-us/articles/217967608-How-to-Upgrade-to-Nexus-Repository-Manager-3

http://www.sonatype.org/nexus/2016/05/11/migrating-to-nexus-repository-3-easy-peasy/

However, to me, this migration method currently seems incompatible with our dogu upgrade. @sdorra, what do you think?

**Comment by robertauer** [comment]
See https://github.com/cloudogu/nexus
