### ISSUE TITLE
CAS extenal LDAP/ActiveDirectory

### ISSUE THREAD

**Issue by sdorra** [cloudogu/ecosystem#199]
It should be possible to bind the CAS authentication against an external LDAP-Server of MS ActiveDirectory. We should modify the start of the dogu to read the settings for server, port, bind user, bind password, search base and filter from etcd. These settings could be written to the [cas.properties](https://github.com/cloudogu/cas/blob/develop/src/main/webapp/WEB-INF/cas.properties) file.

**Comment by mbehlendorf** [comment]
TODO:
-  Implement SSL/startTLS
- check if group-mapping works

**Comment by mbehlendorf** [comment]
group-mapping works
