### ISSUE TITLE
Jenkins cas plugin

### ISSUE THREAD

**Issue by mbehlendorf** [cloudogu/ecosystem#205]
It seems like our jenkins doesn't use cas anymore.
I can access jenkins without getting redirected to cas.
from jenkins.log:
>   WARNING: Failed to run script file:/var/lib/jenkins/init.groovy.d/init02setrealm.groovy
Sep 28 14:16:19 ces docker/jenkins[3091]: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Sep 28 14:16:19 ces docker/jenkins[3091]: /var/lib/jenkins/init.groovy.d/init02setrealm.groovy: 3: unable to resolve class org.jenkinsci.plugins.cas.CasSecurityRealm
Sep 28 14:16:19 ces docker/jenkins[3091]:  @ line 3, column 1.
Sep 28 14:16:19 ces docker/jenkins[3091]:    import org.jenkinsci.plugins.cas.CasSecurityRealm;
Sep 28 14:16:19 ces docker/jenkins[3091]:    ^
Sep 28 14:16:19 ces docker/jenkins[3091]: 
Sep 28 14:16:19 ces docker/jenkins[3091]: /var/lib/jenkins/init.groovy.d/init02setrealm.groovy: 4: unable to resolve class org.jenkinsci.plugins.cas.protocols.Saml11Protocol
Sep 28 14:16:19 ces docker/jenkins[3091]:  @ line 4, column 1.
Sep 28 14:16:19 ces docker/jenkins[3091]:    import org.jenkinsci.plugins.cas.protocols.Saml11Protocol;
Sep 28 14:16:19 ces docker/jenkins[3091]:    ^
Sep 28 14:16:19 ces docker/jenkins[3091]: 
Sep 28 14:16:19 ces docker/jenkins[3091]: 2 errors

**Comment by mbehlendorf** [comment]
already fixed, we just need to update the dogu

**Comment by sdorra** [comment]
The issue is still active

**Comment by sdorra** [comment]
should be fixed with dogu version 2.7.4-1
