### ISSUE TITLE
SonarQube migration to Cloudogu

### ISSUE THREAD

**Issue by robertauer** [cloudogu/ecosystem#207]
This is about the migration of an external SonarQube instance to the SonarQube dogu included in the ecosystem.
One way of doing this is to import a mysqldump of the existing 'sonar' database into the ecosystem mysql instance and import/adapt files of the old SonarQube instance as described [here](http://docs.sonarqube.org/display/SONAR/Upgrading). This leads to permission problems, because the authorization process in the ecosystem is based on cas and the direct login to SonarQube's own user database is no longer possible.
Another way would be the registration of all SonarQube users via the user management and an import of the SonarQube projects. Unfortunately, the export of particular projects is no feature of SonarQube yet and is only possible by using the ['Governance' plugin](http://www.sonarsource.com/products/plugins/governance/), which is not free.
Links regarding this subject:
[http://www.sonarsource.com/2016/06/13/sonarqube-governance-1-0-released/](http://www.sonarsource.com/2016/06/13/sonarqube-governance-1-0-released/)
[http://docs.sonarqube.org/display/PLUG/Project+Move](http://docs.sonarqube.org/display/PLUG/Project+Move)

**Comment by sklein94** [comment]
This is outdated. Issue will be closed.
