### ISSUE TITLE
Redmine: Internal error at 'Information' page access

### ISSUE THREAD

**Issue by robertauer** [cloudogu/ecosystem#221]
When an admin user tries to access the 'Information' page in the Administration section of Redmine, an internal error occurs and the production.log logs the following lines:

> Started GET "/redmine/admin/info" for 10.0.0.6 at 2016-11-16 09:59:18 +0000
Processing by AdminController#info as HTML
  Current user: admin (id=3)
Completed 500 Internal Server Error in 63ms (ActiveRecord: 2.7ms)
RuntimeError (Authentication data not accepted):
  app/models/auth_source_cas.rb:148:in `authenticate'
  app/models/user.rb:306:in `check_password?'
  app/models/user.rb:450:in `default_admin_account_changed?'
  app/controllers/admin_controller.rb:77:in `info'

**Comment by robertauer** [comment]
When the 'Information' page is accessed, Redmine tries to authenticate against cas. This leads to an authentication failure. For detailed information see /var/log/docker/cas.log

**Comment by sdorra** [comment]
Seams to be fixed.
