### ISSUE TITLE
HSTS handling during setup

### ISSUE THREAD

**Issue by schristann** [cloudogu/ecosystem#223]
HSTS is redirecting the user from http://your.instance.here:8080 to https://your.instance.here:8080 on webkit based browsers like Chrome, Safari and Chromium. This prevents the user from setting up his instance. Workaround is using Firefox or using the raw ip address at the moment.
We should handle Strict-Transport-Security:  in the header in order to improve the user experience.

**Comment by sdorra** [comment]
The error occurs only if you are trying to install a ces instance with a fqdn of a domain, which uses Strict-Transport-Security includeSubDomains (such as cloudogu.com). In this case you have to clear the hsts settings for this domain (for chrome `chrome://net-internals/#hsts`). But this behavior ca not be changed on the setup.
