### ISSUE TITLE
Global session timeout

### ISSUE THREAD

**Issue by schnatterer** [cloudogu/ecosystem#226]
As a user, I would love a longer global session timeout, so that I don't have to enter my credentials multiple times a day.

Details: As of now, when working for example with Jenkins, SCMManager and SonarQube via the web, I have to enter my username and password multiple times a day, depending on the session timeout of the individual tools. It would be much more comfortable to have a longer session, like for example on GitHub where a sessions lasts for many days.
A convenient solution would be to have a global property in CES, that is propagated to all dogus. So each instance can configure its own global timeout to suit its needs.

**Comment by sklein94** [comment]
CAS has now configuration which should achieve exactly what you want! Look here: https://github.com/cloudogu/cas/blob/315d61a3a4fe0701db1b377e193fce7eec2cd7bb/dogu.json#L66

If you still think this is an issue, you can reopen it at: https://github.com/cloudogu/cas
