### ISSUE TITLE
Update dogu files & best practices

### ISSUE THREAD

**Issue by robertauer** [cloudogu/ecosystem#235]
Update dogu resources to make Dockerfiles and other scripts more concise and smaller. Also update best practice docs.

- Copy resources with one command
  - cp resource/* /  (needs correct folder structure in resource folder)
- Set environment variables with one command
  - ENV one=1 \ 
 two=2 \ 
etc
- Merge commands of same type, if possible
  - e.g. RUN abcd.sh \ 
 && /install/install.sh \ 
 && ...
- Get and unpack tarballs in one command
  - curl -L ... | tar -xfz (--strip-component=1) -c /targetdir
- Set correct file permissions to avoid chmod/chown commands

**Comment by sklein94** [comment]
This is now contained in our definition of done. I will close this issue.
