### ISSUE TITLE
Fix postfix startup script

### ISSUE THREAD

**Issue by robertauer** [cloudogu/ecosystem#242]
Remove ` >>/var/log/postfix.log 2>&1` from the last line of the startup.sh of postfix to let all log data be written to stdout. This will make sure that all log data ends up in the hosts postfix.log and does not stay inside the container.

**Comment by sdorra** [comment]
Fixed by [42e7f5e9](https://github.com/cloudogu/ecosystem/commit/42e7f5e99be3f9b6fc2765da757023967ace111f). The container uses now rsyslog to forward the mail logs to stdout.
