### ISSUE TITLE
line endings when using git on windows with vagrant

### ISSUE THREAD

**Issue by schristann** [cloudogu/ecosystem#243]
When using windows, the git checkout breaks scripts by adding bad line endings.

**Comment by omilke** [comment]
This bug has been fixed by defining to checkout all files with LF in a [previous commit](https://github.com/cloudogu/ecosystem/commit/f74f4309b52ab7872e415f6b22e44e57485e2be3).

This has been tested on a Windows machine and works independent of the system's _core.autocrlf_ setting.
