### ISSUE TITLE
Re-introduce official Jenkins CAS-Plugin

### ISSUE THREAD

**Issue by omilke** [cloudogu/ecosystem#266]
The official Jenkins CAS Plugin has been disabled. Details are listed in [our corresponding issue](https://github.com/cloudogu/ecosystem/issues/265).

Once available, we will re-introduce the official Jenkins CAS Plugin.

ETA unclear as of 2017-04-12.

**Comment by sdorra** [comment]
Corresponding issue of cas-plugin [#8](https://github.com/fcrespel/jenkins-cas-plugin/issues/8)
