### ISSUE TITLE
ipchange script occasionally doesn't work

### ISSUE THREAD

**Issue by robertauer** [cloudogu/ecosystem#291]
IP has changed on Virtualbox EcoSystem after it was shut down and booted some days later. The log output was:

`
May 15 08:15:33 ces ipchange.sh[1252]: 08:15:33: IP has not changed or last IP (192.168.115.197) is empty or not an IP. Current IP = 192.168.115.197
May 15 08:20:31 ces ipchange.sh[1249]: 08:20:31: IP has not changed or last IP (192.168.115.197) is empty or not an IP. Current IP = 192.168.115.197
May 15 13:46:58 ces ipchange.sh[1271]: 13:46:58: IP has not changed or last IP (192.168.115.197) is empty or not an IP. Current IP = 192.168.115.197
May 19 08:38:46 ces ipchange.sh[1253]: 08:38:46: IP has changed from >192.168.115.197< to >192.168.115.148<
May 19 08:38:46 ces ipchange.sh[1253]: 08:38:46: 192.168.115.148 is a valid IP; setting fqdn
May 19 08:38:46 ces ipchange.sh[1253]: 192.168.115.148
May 19 08:38:47 ces ipchange.sh[1253]: 08:38:47: certificate type is selfsigned
May 19 08:38:47 ces ipchange.sh[1253]: create self sigined certificate for fqdn 192.168.115.148 and primary ip 192.168.115.148
May 19 08:38:47 ces ipchange.sh[1253]: unable to write 'random state'
May 19 08:40:39 ces ipchange.sh[1252]: 08:40:39: IP has not changed or last IP (192.168.115.148) is empty or not an IP. Current IP = 192.168.115.148
May 19 08:45:08 ces ipchange.sh[1256]: 08:45:08: IP has not changed or last IP (192.168.115.148) is empty or not an IP. Current IP = 192.168.115.148
May 19 08:56:54 ces ipchange.sh[1250]: 08:56:54: IP has not changed or last IP (192.168.115.148) is empty or not an IP. Current IP = 192.168.115.148
`

FQDN in etcd was still set to the old IP (197) which was assigned to a new machine in the meantime.
Symptoms were: User tries to load the ces via the new IP, but gets redirected to the old one.

**Comment by robertauer** [comment]
Sometimes even etcd is not available, because the current IP is determined in the ipchange script via functions.sh which apparently fails to do so.

**Comment by ischindler** [comment]
Should be checked again and todos derived.

**Comment by sklein94** [comment]
I worked much with the ecoSystem in a vagrant machine and this never happened to me. So i think this should be fixed!
If it happens again to you, you can reopen this issue.
