### ISSUE TITLE
Redmine build fails

### ISSUE THREAD

**Issue by robertauer** [cloudogu/ecosystem#293]
Currently, the redmine dogu does not seem to build correctly. The following messages are shown:

---
.....
Bundler could not find compatible versions for gem "mini_portile2":
  In Gemfile:
    nokogiri (>= 1.6.7.2) was resolved to 1.6.7.2, which depends on
      mini_portile2 (~> 2.2.0)

    roadie-rails was resolved to 1.0.4, which depends on
      roadie (~> 3.0) was resolved to 3.0.0, which depends on
        nokogiri (~> 1.6.0) was resolved to 1.6.7.2, which depends on
          mini_portile2 (~> 2.0.0.rc2)
Bundler could not find compatible versions for gem "nokogiri":
  In Gemfile:
    nokogiri (>= 1.6.7.2)

    capybara was resolved to 2.14.1, which depends on
      nokogiri (>= 1.3.3)

    rails-html-sanitizer (>= 1.0.3) was resolved to 1.0.3, which depends on
      loofah (~> 2.0) was resolved to 2.0.3, which depends on
        nokogiri (>= 1.5.9)

    roadie-rails was resolved to 1.0.4, which depends on
      roadie (~> 3.0) was resolved to 3.0.0, which depends on
        nokogiri (~> 1.6.0)

    capybara was resolved to 2.14.1, which depends on
      xpath (~> 2.0) was resolved to 2.1.0, which depends on
        nokogiri (~> 1.3)
Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (= 4.2.7.1)

    roadie-rails was resolved to 1.0.0, which depends on
      rails (< 4.2, >= 3.0)
WARNING: Ignoring APKINDEX.c51f8f92.tar.gz: No such file or directory
WARNING: Ignoring APKINDEX.d09172fd.tar.gz: No such file or directory
.....

---
The container is created, but fails to start with the following log message:
`grep: /usr/share/webapps/redmine/config/initializers/secret_token.rb: No such file or directory`

**Comment by cwolfes** [comment]
works for me!
