### ISSUE TITLE
Redirection to /cockpit/undefined after Log-In

### ISSUE THREAD

**Issue by mschwell-mat** [cloudogu/ecosystem#294]
Sometimes (perhaps the very first time a new user logs in?) you get redirected to /cockpit/undefined after successful log-in.
Removing the suffix /undefined in the browser's address leads to the expected site (the cockpit).

**Comment by sdorra** [comment]
We have just released a new version of the cockpit, could please test with the new version (0.3.0)?

**Comment by mschwell-mat** [comment]
I'll test it, but it might take some time because of some workarounds I have to use before updateing because of the missing proxy support.

-----Ursprüngliche Nachricht-----
Von: Sebastian Sdorra [mailto:notifications@github.com] 
Gesendet: Mittwoch, 28. Juni 2017 07:57
An: cloudogu/ecosystem <ecosystem@noreply.github.com>
Cc: Schwellenberg, Matthias <Matthias.Schwellenberg@materna.de>; Author <author@noreply.github.com>
Betreff: Re: [cloudogu/ecosystem] Redirection to /cockpit/undefined after Log-In (#294)

We have just released a new version of the cockpit, could please test with the new version (0.3.0)?

**Comment by ischindler** [comment]
Any updates @mschwell-mat on this one?

**Comment by mschwell-mat** [comment]
Hello Iwan,

I yesterday updated my ecoSystem to the newest Dogu versions. I'm going to test the behavior today before I'm going on vecation.

Regards,
Matthias

-----Ursprüngliche Nachricht-----
Von: Iwan Schindler [mailto:notifications@github.com] 
Gesendet: Donnerstag, 3. August 2017 17:40
An: cloudogu/ecosystem <ecosystem@noreply.github.com>
Cc: Schwellenberg, Matthias <Matthias.Schwellenberg@materna.de>; Mention <mention@noreply.github.com>
Betreff: Re: [cloudogu/ecosystem] Redirection to /cockpit/undefined after Log-In (#294)

Any updates @mschwell-mat <https://github.com/mschwell-mat>  on this one?

**Comment by ischindler** [comment]
We should check whether this is due to a CAS timeout

**Comment by mbehlendorf** [comment]
fixed with cockpit v0.3.6
