### ISSUE TITLE
Redmine: Links to Issues in generated Mails do not work

### ISSUE THREAD

**Issue by mschwell-mat** [cloudogu/ecosystem#295]
In Redmine the Out-of-the-box mail configuration is invalid and leads to non-functional issue links in auto generated mails.
First:
In Redmine the configuration of the base url is split in two parts: One Pull-Down-Menu for http/https and one string for the url itself.
The url is pre-configured to https://<ceshost>...... while in the pull-down menu "HTTP" is selected.
The right way: confiugure the url only with <ceshost>... (without trailing "https://") and select "HTTPS" in the pull down menu.
Second: The generated link contain the namespace "/redmine" two times.

**Comment by sdorra** [comment]
should be fixed with version 3.3.2-4 of the redmine dogu.

**Comment by robertauer** [comment]
Links in emails are still faulty, include /redmine/redmine...
