### ISSUE TITLE
Disable default vagrant user after completion of the setup process

### ISSUE THREAD

**Issue by mschwell-mat** [cloudogu/ecosystem#296]
Currently the default vagrant user (with weak password) ist still available even after the setup process of the appliance has finished.
So everyone is able to connect to the appliance with a priviledged user via ssh without the knowledge of the end users.
After the custom OS admin user has been configured and displayed to the user who ran the initial setup the vagrant default user should be disabled.

**Comment by schristann** [comment]
Hello MSchwell,

this proposal seems legit to me. We will discuss a solution that fits both developer use cases and production use cases. We will soon come back on this issue.

Yours sincerely

Stephan Christann

**Comment by ischindler** [comment]
The vagrant user is just active in the development version of Cloudogu. The production version does not use vagrant to run Cloudogu and therefore the vagrant user will not be included. A Cloudogu version without vagrant can be built with packer (https://github.com/cloudogu/ecosystem/tree/develop/images/template.prod.json).

**Comment by mschwell-mat** [comment]
Hello ischindler,
thank you for your confirmation. Then I would suggest to also put this information onto your web site (cloudogu.com) as there is only explained how to build & start the latest development version with vagrant.
Users might test (and use!) such a "Quick Start" version without knowledge of the security risk.
Cheers,
Matthias

**Comment by ischindler** [comment]
Hello Matthias,
thank you for your suggestion. We are working on an update of our website to reflect such topics. In the meantime we're glad to help whenever we can.
Best regards
Iwan
