### ISSUE TITLE
NGinx 504 Error after weeks of operation

### ISSUE THREAD

**Issue by schristann** [cloudogu/ecosystem#298]
After week of operation the NGinx error happened again. It seem that the dogu that get the most hits over time will get the effect of this error. A restart of NGinx (and not the dogu) will fix this for the next period. Because the redmine dogu gets the most hits this dogu is most likely to be affected by the error.

**Comment by sdorra** [comment]
released version, with improved settings for worker connections and keep alive. Also nginx was upgraded to version 1.13.1. If the bug occurs again, please reopen this issue.
