### ISSUE TITLE
remine plugin installation failing

### ISSUE THREAD

**Issue by schristann** [cloudogu/ecosystem#312]
I just tried installing agile plugin lite into CES (https://www.redmineup.com/pages/plugins/agile?utm_source=redmineorg&utm_medium=free&utm_term=agile&utm_campaign=agiledownload#pricing). I put the extracted .zip into the plungin volume. After that the redmine dogu wont start, because the plugin migration fails.
I tried this with a former version known to work, but that also caused this problem.

**Comment by ischindler** [comment]
Fixed with new redmine version
