### ISSUE TITLE
Username limited to 32 characters

### ISSUE THREAD

**Issue by mporner** [cloudogu/ecosystem#315]
The username in User Management is limited to 32 characters. There are problems with LDAP authentication with email addresses when the email addresses are longer than 32 characters.
The character limit could be increased to 128 characters..

https://github.com/cloudogu/usermgt/blob/develop/src/main/webapp/views/user/edit.html#L20
https://github.com/cloudogu/usermgt/blob/develop/src/main/java/de/triology/universeadm/validation/RDNValidator.java#L42

**Comment by sdorra** [comment]
Fixed with v1.3.2-1 of usermgt dogu.
