### ISSUE TITLE
Directory build missing / not created

### ISSUE THREAD

**Issue by schristann** [cloudogu/ecosystem#324]
On image creation the finalization fails, because the directory build is missing due to not being created and not being delivered through git clone because it was empty. Perhaps the build (through packer) itself can create it? 

PS: There is no documentary how to build an image in the README.md

**Comment by robertauer** [comment]
> On image creation the finalization fails, because the directory build is missing due to not being created and not being delivered through git clone because it was empty. Perhaps the build (through packer) itself can create it?

What kind of image did you try to create and how? QEMU, VMware, Virtualbox? prod or dev?

> PS: There is no documentary how to build an image in the README.md

You can find it in docs/docs/user-guide/image-build.md

**Comment by cwolfes** [comment]
see https://github.com/cloudogu/ecosystem/blob/develop/docs/development/image-build_de.md
