### ISSUE TITLE
Logged-in user name is not updated

### ISSUE THREAD

**Issue by mporner** [cloudogu/ecosystem#325]
If a user logs off from the CES and another user logs in there, the user name is displayed by the previous user in the cockpit.
For example User01 logs out and User02 logs in but sees in the cockpit the user name User01

**Comment by sdorra** [comment]
It looks like an ie caching bug

**Comment by cwolfes** [comment]
yep, i can reproduce this bug in IE11. Maybe a no caching header will fix this problem.

**Comment by cwolfes** [comment]
fixed: https://github.com/cloudogu/cockpit/commit/b09b054bae50d4b992673a4f7454cea6aee7626f
