### ISSUE TITLE
Redmine infopage broken

### ISSUE THREAD

**Issue by schristann** [cloudogu/ecosystem#334]
After installing CES with redmine e.g. https://192.168.115.106/redmine/admin/info with version 3.4.2 - the info page show an error 500.

**Comment by ischindler** [comment]
I've tested this behavior and could not reproduce it. With my version it shows the info page as it should. 
![2017-11-07 15_02_42-informationen - redmine](https://user-images.githubusercontent.com/26225357/32497503-06d90fb4-c3cd-11e7-9ede-262c611acedc.png)
