### ISSUE TITLE
Different users in cockpit and redmine

### ISSUE THREAD

**Issue by mporner** [cloudogu/ecosystem#339]
I logged in as "Testuser" at CAS and changed a dashboard in Cockpit. There I was logged in as "Testuser". Then I changed over the Warp-Menue to Redmine to create a project there. In Redmine I was logged in as "Admin".
I can not reproduce the behavior.

CAS version 4.0.7.12-1
Cockpit version 0.3.3
Redmine version 3.4.2.1

**Comment by ischindler** [comment]
Until now we didn't have the option to reproduce this issue. If it occurs again we would need a description of the individual steps to reproduce it.
