### ISSUE TITLE
Nagios/NRPE Readyness

### ISSUE THREAD

**Issue by schristann** [cloudogu/ecosystem#342]
Maybe we should implement a little nrpe daemon dogu, that provides basic monitoring. For example something like this alpine container:

https://github.com/mikenowak/docker-nrpe/blob/master/Dockerfile

We could also tailor nagios_plugins for our system and add them. We should make shure that nrpe uses ssl and well limited access only for the intended monitoring checks. Maybe the allowed_host could be configured by web ui or setup.json.

**Comment by cwolfes** [comment]
we have a specific premium dogu for that matter. https://github.com/cloudogu/monitoring
