### ISSUE TITLE
Metdown and Spectre

### ISSUE THREAD

**Issue by schristann** [cloudogu/ecosystem#359]
Maybe wie should use Kernel 4.14(patched) or 4.15 on relese 09/10.01.2018. https://insights.ubuntu.com/2018/01/04/ubuntu-updates-for-the-meltdown-spectre-vulnerabilities/

**Comment by robertauer** [comment]
Spectre patch is not yet released: https://wiki.ubuntu.com/SecurityTeam/KnowledgeBase/SpectreAndMeltdown?_ga=2.181863521.710291776.1516613145-946471018.1450270201
