### ISSUE TITLE
Support Split DNS Setup

### ISSUE THREAD

**Issue by schristann** [cloudogu/ecosystem#366]
When using services within local network or dmz, dogus resolve these names to external ip addresses. If dns is restricted to an internal server this will fail anyway completely. There should be a way to configure a dns server that serves the host aswell as the containers.

**Comment by schristann** [comment]
Workaround until implementation:

/etc/systemd/system/docker.service.d/dockeroptions.conf

[Service]
ExecStart=
ExecStart=/usr/bin/dockerd -s btrfs --dns PUYOURDNSSERVERHERE --log-driver=syslog --cluster-store=etcd://127.0.0.1:4001 --cluster-advertise=127.0.0.1:4001
Restart=always

**Comment by schristann** [comment]
Another way to solve this challange would be to make the CES DNS-Bulletproof by add a local resolver with forwarder that is configured in the dockeroptions.conf. This resolver would intercept requests aiming for the FQDN of the CES and forwarding other requests to DNS upstream servers. This could even be a resover dogu.
Additional gain would be minimizing traffic to upstream server caused by CES internal requests.
Upstream DNS server could default to google or to user given servers during setup proccess.

**Comment by ppxl** [comment]
A Split DNS configuration is now supported with the resolution of https://github.com/cloudogu/ces-setup/issues/97. That being said at least [this ces-setup version v0.18.0](https://github.com/cloudogu/ces-setup/releases/tag/v0.18.0) must be installed. This new feature can be leveraged in two ways:

1. Using the Setup UI
2. Using a `setup.json`

Number 1 goes almost without saying: In the `naming` section of the Setup check the checkbox `Use specific internal IP address` and enter an IP address of the CES host which is used to resolve the CES from inside.

Number 2 does a comparable thing in terms of the `setup.json` file. Two new fields are created with in the `naming` section of the file. Enter the same information as just discussed into the properties `useInternalIp` and `internalIp`. A snipped from the `setup.json` could look like this, just add the two  new properties to your other `setup.json` file:

```javascript
"naming": {
    "useInternalIp": true,
    "internalIp": "10.0.2.15"
}
```

**Comment by cwolfes** [comment]
seems to be implemented. :+1:
