### ISSUE TITLE
CES Build broken

### ISSUE THREAD

**Issue by schristann** [cloudogu/ecosystem#372]
Currently the packer build is broken due to ubuntus server images changed. Therefore neither the image is found nor the sha256 checksum is correct. Here, have my fix for that:

diff --git a/images/template.prod.json b/images/template.prod.json
index c9093a4..0c68955 100644
--- a/images/template.prod.json
+++ b/images/template.prod.json
@@ -14,9 +14,9 @@
                        "vm_name": "{{user `vm_name`}}",
                        "guest_os_type": "Ubuntu_64",
                        "iso_urls": [
-                               "http://releases.ubuntu.com/xenial/ubuntu-16.04.4-server-amd64.iso"
+                               "http://releases.ubuntu.com/xenial/ubuntu-16.04.5-server-amd64.iso"
                        ],
-                       "iso_checksum": "0a03608988cfd2e50567990dc8be96fb3c501e198e2e6efcb846d89efc7b89f2",
+                       "iso_checksum": "c94de1cc2e10160f325eb54638a5b5aa38f181d60ee33dae9578d96d932ee5f8",
                        "iso_checksum_type": "sha256",
                        "ssh_username": "{{user `username`}}",
                        "ssh_password": "{{user `password`}}",
@@ -65,9 +65,9 @@
                        "vm_name": "{{user `vm_name`}}",
                        "guest_os_type": "ubuntu-64",
:...skipping...
diff --git a/images/template.prod.json b/images/template.prod.json
index c9093a4..0c68955 100644
--- a/images/template.prod.json
+++ b/images/template.prod.json
@@ -14,9 +14,9 @@
                        "vm_name": "{{user `vm_name`}}",
                        "guest_os_type": "Ubuntu_64",
                        "iso_urls": [
-                               "http://releases.ubuntu.com/xenial/ubuntu-16.04.4-server-amd64.iso"
+                               "http://releases.ubuntu.com/xenial/ubuntu-16.04.5-server-amd64.iso"
                        ],
-                       "iso_checksum": "0a03608988cfd2e50567990dc8be96fb3c501e198e2e6efcb846d89efc7b89f2",
+                       "iso_checksum": "c94de1cc2e10160f325eb54638a5b5aa38f181d60ee33dae9578d96d932ee5f8",
                        "iso_checksum_type": "sha256",
                        "ssh_username": "{{user `username`}}",
                        "ssh_password": "{{user `password`}}",
@@ -65,9 +65,9 @@
                        "vm_name": "{{user `vm_name`}}",
                        "guest_os_type": "ubuntu-64",
                        "iso_urls": [
-                               "http://releases.ubuntu.com/xenial/ubuntu-16.04.4-server-amd64.iso"
+                               "http://releases.ubuntu.com/xenial/ubuntu-16.04.5-server-amd64.iso"
                        ],
-                       "iso_checksum": "0a03608988cfd2e50567990dc8be96fb3c501e198e2e6efcb846d89efc7b89f2",
+                       "iso_checksum": "c94de1cc2e10160f325eb54638a5b5aa38f181d60ee33dae9578d96d932ee5f8",
                        "iso_checksum_type": "sha256",
                        "ssh_username": "{{user `username`}}",
                        "ssh_password": "{{user `password`}}",
@@ -96,9 +96,9 @@
                        "format": "qcow2",
                        "vm_name": "{{user `vm_name`}}",
                        "iso_urls": [
-                               "http://releases.ubuntu.com/xenial/ubuntu-16.04.4-server-amd64.iso"
+                               "http://releases.ubuntu.com/xenial/ubuntu-16.04.5-server-amd64.iso"
                        ],
-                       "iso_checksum": "0a03608988cfd2e50567990dc8be96fb3c501e198e2e6efcb846d89efc7b89f2",
+                       "iso_checksum": "c94de1cc2e10160f325eb54638a5b5aa38f181d60ee33dae9578d96d932ee5f8",
                        "iso_checksum_type": "sha256",
                        "ssh_username": "{{user `username`}}",
                        "ssh_password": "{{user `password`}}",
~
~
~
~
~
~
~
~
~

**Comment by robertauer** [comment]
Fixed since https://github.com/cloudogu/ecosystem/commit/949ef46f363993806a88e87cebd7f90ce3a98866
