### ISSUE TITLE
installation Fail - external directory / ldap dogu

### ISSUE THREAD

**Issue by schristann** [cloudogu/ecosystem#373]
install ces using:
- external directory service
- selecting alls dogus via all button

Dependencies will break and after install the system is deranged and will not work.

**Comment by robertauer** [comment]
@schristann please tell us more about the circumstances:
- Which kind of external directory service did you use?
- What do you mean by "dependencies will break" and how is the system "deranged"?
- What kind of hardware did you use? Did your system have at least 8GB of RAM?

**Comment by schristann** [comment]
Hello, the type of the external directory does not matter at all. If you chose to use an external directory as base for user accounts the selection of install "all" dogus should not lead to an half installed embedded ldap. Therefore the reason for this will probably be a gap in the dependency management or dependency management is not used when choosing the "all" option on the dogu selection page during setup. The used hardware had 2 cpu cores an 10 gigs of ram. The logs after installation was finished "successfully" showed on startup (we supervised journalctl and /var/log/docker/*.log) that there was a problem with the ldap dogu - what probably is complete out of discussion to be installed in this case.

**Comment by robertauer** [comment]
This seems to be an issue with the [ces-setup](https://github.com/cloudogu/ces-setup) which was already declared fixed in https://github.com/cloudogu/ces-setup/issues/35.

**Comment by cwolfes** [comment]
Issue will be closed here! See cloudogu/ces-setup#35 for potential fix.
