### ISSUE TITLE
Redmine messages for new admins

### ISSUE THREAD

**Issue by schristann** [cloudogu/ecosystem#374]
The redmine messages sent for information about new admins generated are looking like this:

Administrator bugtracker was added.
Users

User: WGE
IP address: 172.18.0.3
Date: 10/23/2018 08:45 AM

The IP-Address can be identified as nginx container ip. This should be the address of the client.

**Comment by cwolfes** [comment]
if still relevant please reopen it https://github.com/cloudogu/redmine/issues
