### ISSUE TITLE
Sonatype Nexus - Gruppenmitgliedschaften

### ISSUE THREAD

**Issue by schristann** [cloudogu/ecosystem#375]
- Bei Verwendung eines eigenen Verzeichnisdienstes, können Dogu Admins die Gruppen aus dem Verzeichnisdienst mit Benutzern füllen, die dort gar keine Mitgliedschaft haben. 
- Bei erneuter Anmeldung werden diese Mitgliedschaften auch nicht aktualisiert oder korrigiert. 
- Wird einem Benutzer nachträglich eine Gruppe entzogen erfolgt also ebenfalls auch keine Aktualisierung.

Besonders in größeren Unternehmen mit komplexen Strukturen muss auch der Entzug von Rechten über den Verzeichnisdienst funktionieren um keine Administrationsmonster zu schaffen?!

**Comment by cwolfes** [comment]
if still relevant please reopen it here https://github.com/cloudogu/nexus/issues
