### ISSUE TITLE
How to update the SSL certificate used in cloudogu dogus ?

### ISSUE THREAD

**Issue by mwasyou** [cloudogu/ecosystem#383]
I have been using cloudogu (ecosystem) for almost a year now. Thank you @cloudogu team for this great product.

I'm facing a problem of certificate expiration, which for example, prevents jenkins to access to code in scm-universe git repository

Here the error log as reported by jenkins :

```
Failed to connect to repository : Command "git ls-remote -h -- https://my.cloudogu.instance/scm/git/my-project HEAD" returned status code 128:
stdout:
stderr: fatal: unable to access 'https://my.cloudogu.instance/scm/git/my-project': SSL certificate problem: certificate has expired
```

Since all dogus (jenkins, scm-manager, sonarqube, nginx ...) face the same pb of certificate expiration, I guess there is a way to be used in order to generate a new self signed certificate the will be used by all dogus.

Could anyone please give some hints in this direction.

**Comment by robertauer** [comment]
To generate new self signed certificates, just run /usr/local/bin/ssl.sh and restart the system.
