### ISSUE TITLE
Bug: Authentication token of type [class com.cloudogu.scm.cas.browser.CasToken] could not be authenticated by any configured realms.

### ISSUE THREAD

**Issue by jzachacas** [cloudogu/ecosystem#418]
With the current cloudogu eco system there seems to be an issue with the CAS or the ldap dogu. Login to SCM manager is not possible.

I created two fresh VMs to test this. First from the provided ova file, later with a new vagrant built following the readme.
I used the web setup at port :8080, used default values whereever posssible and tried to login with the first user in the scm-manager.

After login, when being redirected to scm-manager, I see the following error in the browser window:

> Authentication token of type [class com.cloudogu.scm.cas.browser.CasToken] could not be authenticated by any configured realms.  Please ensure that at least one realm can authenticate these tokens.

The Url reads https://[local-ip]/scm/api/v2/cas/auth/v2:2jUYYrdCA_e37bYfbMtKXrxQzlCfgCyxbUT36ix829zw?ticket=ST-7-bFGlLrek1GKB6kNvnnRb-cas.ces.local

HTTP status is 401.

Redirect to usermgt works, I am correctly logged-in there.

The dogu versions to reproduce this issue are:

```
NAME         VERSION      DISPLAYNAME                     DESCRIPTION
cas          4.0.7.20-14  Central Authentication Service  The Central Authentication Service (CAS) is a s...
cockpit      1.1.6-1      Cockpit                         Dashboard for the Cloudogu EcoSystem
ldap         2.4.48-3     OpenLDAP                        OpenLDAP server for user and group management.
nginx        1.17.8-8     Nginx                           Nginx WebServer.
postfix      3.2.4-1      Postfix                         Postfix - Mail Transfer Agent
postgresql   12.5-2       PostgreSQL                      PostgreSQL Database.
registrator  0.8.1-1      Registrator                     Service registry bridge for Docker with pluggab...
scm          2.12.0-1     SCM-Manager                     The easiest way to share and manage your Git, M...
usermgt      1.4.1-2      User Management                 User and Group Management.
```

My last _working_ setup contained:
```
NAME         VERSION      DISPLAYNAME                     DESCRIPTION
cas          4.0.7.20-13  Central Authentication Service  The Central Authentication Service (CAS) is a s...
cockpit      1.1.5-1      Cockpit                         Dashboard for the Cloudogu EcoSystem
ldap         2.4.48-2     OpenLDAP                        OpenLDAP server for user and group management.
nginx        1.17.8-6     Nginx                           Nginx WebServer.
postfix      3.2.4-1      Postfix                         Postfix - Mail Transfer Agent
postgresql   12.5-2       PostgreSQL                      PostgreSQL Database.
registrator  0.7.0-1      Registrator                     Service registry bridge for Docker with pluggab...
scm          2.12.0-1     SCM-Manager                     The easiest way to share and manage your Git, M...
usermgt      1.4.1-2      User Management                 User and Group Management.
```

I could not find any interesting lines in the log files that would provide more insight.

**Comment by Subaro** [comment]
Hi, thank you for your detailed report.

We could not reproduce the issue with the vagrant setup.  

Could you provide the following information for further investigation:

- The logs for the SCM-Manager (`/var/logs/docker/scm.log`)
- The FQDN configured for your ecosystem

**Comment by jzachacas** [comment]
Please find scm.log attached.

The FQDN matches the IP:
```
ces-admin@ces:~$ etcdctl get /config/_global/fqdn
192.168.56.2

```
I also did some experiments with changing the FQDN to match a host name hardcoded in my local hosts file with no success.

[scm.log](https://github.com/cloudogu/ecosystem/files/5842856/scm.log)

**Comment by Subaro** [comment]
The SCM-Log seems fine. 

Could you provide more information on your browser and export the browser network traffic as HAR file? 

Guide:
1. Log out from the ecosystem
2. Click `SCM-Manager` in the Warp-Menu -> Login-Page should appear
3. Open the developer tools on your browser and switch to the `Network` area. Let it open.
4. Reproduce the problem (Login)
5. Export the Network information in the developer tools as HAR-file

More Information on enabling Debug-Tools and exporting HAR-files can be found [here](https://support.box.com/hc/en-us/articles/360043696054-How-to-Generate-Network-Captures-for-Troubleshooting#:~:text=Click%20the%20Console%20tab%20and,pane%20and%20select%20Export%20HAR.). Thank you.

**Comment by jzachacas** [comment]
Please find the zipped har file attached. 

I am getting the same error with Edge 87.0.664.75 and Chromium 87.0.4280.141.

[192.168.56.2.har.zip](https://github.com/cloudogu/ecosystem/files/5843372/192.168.56.2.har.zip)

**Comment by Subaro** [comment]
Could you provide the CAS log with log level set to debug?

1) Set log level to `debug`: `cesapp edit-config cas logging/root DEBUG`
2) Restart cas `docker restart cas`
3) Reproduce Problem
4) `/var/logs/docker/cas.log`

**Comment by jzachacas** [comment]
Gladly.

[cas_debug.zip](https://github.com/cloudogu/ecosystem/files/5843658/cas_debug.zip)

**Comment by Subaro** [comment]
Currently we do not know why this problem occurs. We will continue to investigate the problem. However, we thank you for your quick response time.

To allow you to continue using your previous setup, we have created a `setup.json`. The file must be placed in the ecosystem folder (besides the .Vagrantfile). Then a new machine must be created with `vagrant destroy && vagrant up`. In the setup for the browser a registration of the instance is necessary. For more information about this mechanism visit https://github.com/cloudogu/ecosystem/blob/develop/docs/docs/user-guide/setup-json_de.md

[setup.zip](https://github.com/cloudogu/ecosystem/files/5844016/setup.zip)

**Comment by jzachacas** [comment]
Thank you very much for your quick response. I can confirm that the VM with the setup.json you provided works like a charm.
I was able to login to scm, create a new repo, then perform checkout and push.

**Comment by jzachacas** [comment]
Out of interest I updated all dogus to the latest version in the VM I created with the setup.json. The problem does not reappear. It seems something during the initial installation phase is broken.

**Comment by Subaro** [comment]
Hello, it seems that the SCM-Manager cannot handle E-Mail without top level domain. This happens in your case as your E-Mail is configured as `admin@localhost`. You could change your E-Mail address accordingly and it should work. 

1) Log into usermgt
2) Change E-Mail to `admin@localhost.de`
3) Logout
4) Log-In
5) Visit SCM-Manager

We aim to make E-Mails without top level valid in the SCM. Thank you for your findings.

**Comment by jzachacas** [comment]
Just to clarify: 
In can confirm that using an E-mail with FQDN like admin@localhost.de is a valid work-around.

I do not require addresses like admin@localhost to be supported.

I consider the issue to be only the missing validation on FQDNs in E-mail addresses in the Web-based installation wizard.
